<?php
$this->title = "Test";
$this->headTitle($this->title);
$this->headScript()->appendFile('scripts/index/index.js');
$this->headLink()->appendStylesheet('styles/index/index.css');
?>

<script type="text/template" id="gallery-categories">
</script>

<script type="text/template" id="gallery-category">
    <a href="#" class="thumbnail">
        <img src="<%= imagePath %>" alt="" />
    </a>
</script>