<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Portfolio');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery-ui/jquery-ui-1.10.0.custom.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/bootstrap/bootstrap.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/underscore.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/json2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.babysitter.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.wreqr.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.marionette.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.relational.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery.timers-1.2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery.galleryview-3.0-dev.js"></script>

    <link href="<?php echo $this->baseUrl(); ?>/styles/jquery-ui/jquery-ui-1.10.0.custom.min.css" media="screen" rel="stylesheet" type="text/css" />

    <link href="<?php echo $this->baseUrl(); ?>/styles/bootstrap/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl(); ?>/styles/bootstrap/bootstrap-responsive.min.css" media="screen" rel="stylesheet" type="text/css" />

    <link href="<?php echo $this->baseUrl(); ?>/styles/layout.css" media="screen" rel="stylesheet" type="text/css" />

    <link href="<?php echo $this->baseUrl(); ?>/styles/galleryview/jquery.galleryview-3.0-dev.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Starmera</a>
          <div id="navbar-div" class="nav-collapse collapse">
            <ul class="nav">
              <li id="navbar-li-home"><a href="#">Home</a></li>
              <li id="navbar-li-gallery"><a href="#gallery">Gallery</a></li>
              <li id="navbar-li-contact"><a href="#contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
              <li id="navbar-li-blog"><a href="#blog">Blog</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div id="main-container" class="container">
        <div id="content"></div>
        <?php echo $this->layout()->content; ?>
        <hr>
        <footer>
          <p>&copy; <a href="http://www.davidgerth.com">David Gerth</a> 2013</p>
        </footer>
    </div>
<?php echo $this->headScript(); ?>
<?php echo $this->headLink(); ?>
</body>
</html>