<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Portfolio');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery-ui/jquery-ui-1.10.0.custom.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/bootstrap/bootstrap.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/underscore.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/json2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.babysitter.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.wreqr.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/backbone.marionette/backbone.marionette.min.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery.timers-1.2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/jquery/jquery.galleryview-3.0-dev.js"></script>

    <link href="<?php echo $this->baseUrl(); ?>/styles/jquery-ui/jquery-ui-1.10.0.custom.min.css" media="screen" rel="stylesheet" type="text/css" />

    <link href="<?php echo $this->baseUrl(); ?>/styles/bootstrap/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl(); ?>/styles/bootstrap/bootstrap-responsive.min.css" media="screen" rel="stylesheet" type="text/css" />

    <link href="<?php echo $this->baseUrl(); ?>/styles/layout.css" media="screen" rel="stylesheet" type="text/css" />

    <link href="<?php echo $this->baseUrl(); ?>/styles/galleryview/jquery.galleryview-3.0-dev.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#"><?php echo $this->escape($this->title); ?></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="hero-unit">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
      </div>

    <div id="content">
      <?php echo $this->layout()->content; ?>
    </div>

    <div class="row">
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div>
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
     </div>
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div>
    </div>

    <footer>
      <p>&copy; <a href="http://www.davidgerth.com">David Gerth</a> 2013</p>
    </footer>

    </div>
<?php echo $this->headScript(); ?>
<?php echo $this->headLink(); ?>
</body>
</html>